use_frameworks!

platform :ios, '8.0'

target 'NITools_Example' do
  pod 'NITools', :path => '../'
  
  target 'NITools_Tests' do
    inherit! :search_paths

    
  end
end

#Xcode里配置：项目名->Target->Build Settings->Enable BitCode中设置为NO就可以了.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

